### ISSUE TITLE
关于判断设备方向时默认AVCaptureVideoOrientationLandscapeRight

### ISSUE THREAD

**Issue by koreadragon** [cdcyd/CCCamera#1]
`// 当前设备取向
- (AVCaptureVideoOrientation)currentVideoOrientation{
    AVCaptureVideoOrientation orientation;
    switch (self.motionManager.deviceOrientation) {
        case UIDeviceOrientationPortrait:
            orientation = AVCaptureVideoOrientationPortrait;
            break;
        case UIDeviceOrientationLandscapeRight:
            orientation = AVCaptureVideoOrientationLandscapeLeft;
            break;
        case UIDeviceOrientationPortraitUpsideDown:
            orientation = AVCaptureVideoOrientationPortraitUpsideDown;
            break;
        default:
            orientation = AVCaptureVideoOrientationLandscapeRight;
            break;
    }
    return orientation;
}`

为什么默认是`AVCaptureVideoOrientationLandscapeRight `，有点不理解，帮忙解释下，谢谢

**Comment by cdcyd** [comment]
right只是一个例子，你可以根据实际需求调整
